### ISSUE TITLE
Add custom generator sample in readme

### ISSUE THREAD

**Issue by rusinikita** [flyingmutant/rapid#25]
Goal: Show extensibility with custom generator and generator result filter.

Problem: User must read the source code to figure out not simple var generation. He wants the generation of slices, structs, ids.

```
type testStruct struct {
	id, value int
	name      string
}

func TestExample(t *testing.T) {
	generatedIds := map[int]bool{}

	gen := rapid.Custom(func(rt *rapid.T) testStruct {
		id := rapid.Int().Filter(func(v int) bool {
			return !generatedIds[v]
		}).Draw(rt, "id").(int)

		generatedIds[id] = true

		return testStruct{
			id:    id,
			value: rapid.Int().Draw(rt, "value").(int),
			name:  rapid.String().Draw(rt, "name").(string),
		}
	})
	
	rapid.Check(t, func(t *rapid.T) {
		generatedIds = map[int]bool{}

                 testSlice1 := rapid.SliceOf(gen).Draw(t, "test_slice1").([]testSamer)
		testSlice2 := rapid.SliceOf(gen).Draw(t, "test_slice2").([]testSamer)

		mergeResult := Merge(testSlice1, testSlice2)
		revertedResult := Remove(mergeResult, testSlice2)
		
		assert.Equal(t, testSlice, revertedResult)
	})
}
```

I will try to figure out a better sample for PR.

Is this a good idea?

**Comment by flyingmutant** [comment]
Thanks for the idea, I'll try to come up with a good thing to include into the README. The existing documentation is probably not very discoverable; maybe giving better names to examples will help a bit as well.

**Comment by morganhein** [comment]
I would love to use this package, but right now with 90% of the methods not having basic documentation, and rich objects are no-obvious for usage in rapid, I easily deduce how to test my objects, let alone in good faith suggest others on my team use this. I really want to, but without documentation it's just too big a hurdle, especially considering property testing is not an automatic "gimme" in general yet.

**Comment by flyingmutant** [comment]
Yep, documentation is definitely lacking right now. I hope to find some time around New Year to improve it, with the goal of releasing `v1.0` with better docs. By the way, new [`Make[V any]`](https://pkg.go.dev/pgregory.net/rapid#Make) generator should make it easier to generate a lot of data types with mininal effort.

**Comment by flyingmutant** [comment]
At its core, rapid does a fairly simple thing: generates random data based on the specification you provide, and check properties that you define on the generated data.

Checking is easy -- you simply write `if` statements and call something like `t.Fatalf` when things look wrong.

Generating is a bit more involved. When you construct a `Generator`, nothing happens: `Generator` is just a specification of how to `draw` the data you want. When you call `draw`, rapid will take some bytes from its internal random bitstream, use them to construct the value based on the `Generator` specification, and track how the random bytes used correspond to the value (and its subparts). This knowledge about the structure of the values being generated, as well as their relationship with the parts of the bitstream allows rapid to intelligently and automatically minify any failure found.

I don't like the name `draw` very much; I've used it in part because Hypothesis (which I regard very high) [does the same](https://hypothesis.readthedocs.io/en/latest/data.html#drawing-interactively-in-tests).

**Comment by morganhein** [comment]
@flyingmutant Thanks! This is exactly what I think I was missing. Would you like a PR with some examples/documentation based on my knowledge?

**Comment by flyingmutant** [comment]
> @flyingmutant Thanks! This is exactly what I think I was missing. Would you like a PR with some examples/documentation based on my knowledge? 

That'd be great, if you don't mind sending something that might not be merged as-is, but for example used as a basis for the 1.0 docs later.

**Comment by flyingmutant** [comment]
Closing in favor of #43.
