### ISSUE TITLE
Add Map function for Generator

### ISSUE THREAD

**Issue by elliot-u410** [flyingmutant/rapid#45]
Love this library! Thank you!

Right now if I want to map a function over a generator, I must use `rapid.Custom`. Would a simpler `Map` function be possible where it lets me simply define the translation between two types?

**Comment by flyingmutant** [comment]
Thanks for the kind words!

To map a function over a generator, you should use [`Transform`](https://pkg.go.dev/pgregory.net/rapid#Transform). Before generics it was a method of the `Generator` called `Map`, but since methods can't be generic in Go, it became a top-level function (and was renamed to `Transform` to not be confused with the [`MapOf`](https://pkg.go.dev/pgregory.net/rapid#MapOf) series of generators).

Maybe it is a good idea to rename `Transform` to `Map`, hmm.

**Comment by elliot-u410** [comment]
Ah, I'm not sure how I missed that. As long as it exists, the name isn't as important to me. Thank you.

**Comment by flyingmutant** [comment]
(I'll leave this open for some time so that I don't forget about possible renaming).
